easy_admin:
  entities:
    # List the entity class name you want to manage
    Player:
      class: App\Entity\Player
    Army:
         class: App\Entity\Army
    Unit:
          class: App\Entity\Unit
    UnitType:
          class: App\Entity\UnitType
    User:
      class: App\Entity\User
      form:
        fields:
          - username
          - email
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

