#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    defaults:
        _controller: App\Controller\SecurityController:loginAction

login_check:
    path: /login_check

logout:
    path: /logout
